"""3_app_streamlit

Automatically generated by Colab.

Original file is located at
https://colab.research.google.com/drive/17PWY_j8CJmz4Ub6oSjfER4X-CiDF1sHd
"""

"""
Datathon Passos Mágicos — Fase 5 (POSTECH)
App Streamlit — Ferramenta de apoio para identificar risco de defasagem

Como rodar localmente:
    streamlit run 3_app_streamlit.py

Como fazer o deploy (Streamlit Community Cloud):
    1. Suba esta pasta inteira ("tech_challenge_5_datathon") para um repositório no GitHub,
       incluindo a subpasta "modelo/" com o arquivo pipeline_risco_defasagem.joblib
       (gerado ao rodar o notebook 2_modelo_preditivo_risco_defasagem.ipynb) e o
       arquivo requirements.txt.
    2. Em https://share.streamlit.io , clique em "New app", aponte para o repositório
       e selecione este arquivo (3_app_streamlit.py) como "Main file path".
    3. Deploy. Pronto — a URL pública pode ser usada pela equipe da Passos Mágicos.
"""

import os
import numpy as np
import pandas as pd
import streamlit as st
import joblib


#Configuração da página

st.set_page_config(
    page_title="Passos Mágicos — Risco de Defasagem",
    page_icon="🧭",
    layout="wide",
)

ORDEM_PEDRA = ["Quartzo", "Agata", "Ametista", "Topazio"]
PEDRA_LABELS = {"Quartzo": "Quartzo", "Agata": "Ágata", "Ametista": "Ametista", "Topazio": "Topázio"}

CAMINHOS_MODELO_CANDIDATOS = [
    "modelo/pipeline_risco_defasagem.joblib",
    "./modelo/pipeline_risco_defasagem.joblib",
    os.path.join(os.path.dirname(__file__), "modelo", "pipeline_risco_defasagem.joblib"),
]


@st.cache_resource(show_spinner="Carregando modelo treinado...")
def carrega_modelo():
    for caminho in CAMINHOS_MODELO_CANDIDATOS:
        if os.path.exists(caminho):
            return joblib.load(caminho), caminho
    return None, None


def monta_linha_features(dados: dict, meta: dict) -> pd.DataFrame:
    """Monta um DataFrame de 1 linha no formato esperado pelo pipeline."""
    linha = {}
    for col in meta["features_num"]:
        linha[col] = dados.get(col, np.nan)
    for col in meta["features_flag"]:
        linha[col] = dados.get(col, 0)
    for col in meta["features_cat"]:
        linha[col] = dados.get(col, np.nan)
    return pd.DataFrame([linha])


def categoria_risco(p: float) -> tuple:
    if p >= 0.66:
        return "Alto risco", "🔴"
    elif p >= 0.33:
        return "Risco moderado", "🟡"
    else:
        return "Baixo risco", "🟢"



#Cabeçalho

st.title("🧭 Risco de Defasagem — Passos Mágicos")
st.caption(
    "Ferramenta de apoio à decisão pedagógica, construída a partir do PEDE "
    "(Pesquisa Extensiva do Desenvolvimento Educacional) 2022-2024. "
    "Estima a probabilidade de um aluno estar (ou entrar) em situação de "
    "defasagem de fase, a partir dos indicadores comportamentais e do "
    "histórico do aluno."
)

modelo_dict, caminho_usado = carrega_modelo()

if modelo_dict is None:
    st.error(
        "Não encontrei o arquivo do modelo treinado "
        "(`modelo/pipeline_risco_defasagem.joblib`).\n\n"
        "Rode o notebook `2_modelo_preditivo_risco_defasagem.ipynb` primeiro — "
        "ele treina o modelo e salva esse arquivo. Depois, garanta que a pasta "
        "`modelo/` está no mesmo diretório deste app (ou no mesmo repositório, "
        "se for rodar no Streamlit Community Cloud)."
    )
    st.stop()

pipeline = modelo_dict["pipeline"]
metricas = modelo_dict.get("metricas_validacao", {})

with st.expander("ℹ️ Sobre o modelo", expanded=False):
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Modelo", metricas.get("modelo", "—"))
    c2.metric("ROC-AUC", f"{metricas.get('roc_auc', 0):.3f}")
    c3.metric("Recall (risco)", f"{metricas.get('recall', 0):.1%}")
    c4.metric("F1-score", f"{metricas.get('f1', 0):.3f}")
    st.markdown(
        "O alvo do modelo é **risco de defasagem**: probabilidade de o aluno "
        "estar abaixo da fase ideal para sua idade (IAN 'Moderada' ou "
        "'Severa'). O modelo foi treinado com Gradient Boosting sobre dados "
        "de 2022 a 2024 da Passos Mágicos, evitando o uso de indicadores que "
        "vazariam a resposta (IAN, Fase, Defasagem, INDE do ano corrente) — "
        "veja o racional completo no notebook de modelagem."
    )

st.divider()

aba_individual, aba_lote = st.tabs(["👤 Avaliar um aluno", "📄 Avaliar em lote (CSV)"])


#ABA 1 — Avaliação individual

with aba_individual:
    st.subheader("Indicadores do aluno (ciclo atual)")
    st.caption("Preencha com os valores mais recentes disponíveis para o aluno (escala 0 a 10).")

    col1, col2, col3 = st.columns(3)
    with col1:
        ida = st.slider("IDA — Desempenho acadêmico", 0.0, 10.0, 6.0, 0.1)
        ieg = st.slider("IEG — Engajamento", 0.0, 10.0, 6.0, 0.1)
    with col2:
        iaa = st.slider("IAA — Autoavaliação", 0.0, 10.0, 6.0, 0.1)
        ips = st.slider("IPS — Psicossocial", 0.0, 10.0, 6.0, 0.1)
    with col3:
        ipv = st.slider("IPV — Ponto de virada", 0.0, 10.0, 6.0, 0.1)
        tem_ipp = not st.checkbox("Não tenho avaliação de IPP para este aluno", value=False)
        ipp = st.slider("IPP — Psicopedagógico", 0.0, 10.0, 6.0, 0.1, disabled=not tem_ipp)

    st.subheader("Perfil e histórico do aluno")
    col4, col5, col6 = st.columns(3)
    with col4:
        idade = st.number_input("Idade", min_value=5, max_value=30, value=12)
        genero = st.selectbox("Gênero", ["Feminino", "Masculino"])
    with col5:
        tempo_na_associacao = st.number_input("Tempo na Passos Mágicos (anos)", min_value=0, max_value=15, value=1)
        n_avaliacoes = st.number_input("Número de avaliações registradas", min_value=0, max_value=10, value=4)
    with col6:
        rede_ensino = st.selectbox("Rede de ensino", ["Pública", "Privada", "Outro/Não informado"])

    st.subheader("Histórico do ciclo anterior (opcional, mas melhora a previsão)")
    col7, col8 = st.columns(2)
    with col7:
        tem_pedra_ant = not st.checkbox("Aluno novo — sem Pedra do ciclo anterior", value=False)
        pedra_ant_label = st.selectbox(
            "Pedra no ciclo anterior",
            [PEDRA_LABELS[p] for p in ORDEM_PEDRA],
            disabled=not tem_pedra_ant,
        )
    with col8:
        tem_inde_ant = not st.checkbox("Aluno novo — sem INDE do ciclo anterior", value=False)
        inde_ant = st.number_input(
            "INDE no ciclo anterior", min_value=0.0, max_value=10.0, value=6.5, step=0.1,
            disabled=not tem_inde_ant,
        )

    st.divider()
    calcular = st.button("Calcular risco de defasagem", type="primary", use_container_width=True)

    if calcular:
        pedra_ant_valor = ORDEM_PEDRA[[PEDRA_LABELS[p] for p in ORDEM_PEDRA].index(pedra_ant_label)] if tem_pedra_ant else None
        dados = {
            "iaa": iaa, "ieg": ieg, "ips": ips,
            "ipp": ipp if tem_ipp else np.nan,
            "ida": ida, "ipv": ipv,
            "idade": idade,
            "tempo_na_associacao": tempo_na_associacao,
            "n_avaliacoes": n_avaliacoes,
            "inde_ano_anterior": inde_ant if tem_inde_ant else np.nan,
            "pedra_ano_anterior_ord": ORDEM_PEDRA.index(pedra_ant_valor) if tem_pedra_ant else -1,
            "tem_historico_pedra": int(tem_pedra_ant),
            "tem_ipp": int(tem_ipp),
            "tem_inde_anterior": int(tem_inde_ant),
            "genero": genero,
            "rede_ensino": rede_ensino,
        }
        linha = monta_linha_features(dados, modelo_dict)
        proba = float(pipeline.predict_proba(linha)[0, 1])
        categoria, emoji = categoria_risco(proba)

        st.markdown("### Resultado")
        r1, r2 = st.columns([1, 2])
        with r1:
            st.metric("Probabilidade de risco de defasagem", f"{proba:.0%}")
            st.markdown(f"## {emoji} {categoria}")
        with r2:
            st.progress(proba)
            if categoria == "Alto risco":
                st.warning(
                    "Sugestão: priorizar este aluno para acompanhamento pedagógico "
                    "e/ou psicopedagógico mais próximo neste ciclo."
                )
            elif categoria == "Risco moderado":
                st.info(
                    "Sugestão: manter monitoramento — vale acompanhar a evolução "
                    "do engajamento (IEG) e desempenho (IDA) no próximo ciclo."
                )
            else:
                st.success("Sugestão: aluno com bom perfil de adequação de fase neste momento.")

        st.caption(
            "Este é um resultado probabilístico de apoio à decisão — não substitui "
            "a avaliação da equipe pedagógica e psicopedagógica da Passos Mágicos."
        )


#ABA 2 — Avaliação em lote

with aba_lote:
    st.subheader("Avaliar vários alunos de uma vez")
    st.markdown(
        "Envie um CSV com uma linha por aluno. Colunas esperadas "
        "(nomes exatamente iguais, mas a ordem não importa):"
    )
    colunas_esperadas = (
        modelo_dict["features_num"][:-1]  #tudo exceto pedra_ano_anterior_ord (tratada à parte)
        + ["pedra_ano_anterior"]
        + modelo_dict["features_cat"]
    )
    st.code(", ".join(colunas_esperadas), language=None)
    st.caption(
        "`pedra_ano_anterior` deve ser um destes valores (ou vazio, se o aluno "
        "for novo): Quartzo, Agata, Ametista, Topazio. Campos numéricos podem "
        "ficar vazios se o dado não existir — o modelo trata isso automaticamente."
    )

    modelo_csv = pd.DataFrame([{c: "" for c in colunas_esperadas}])
    st.download_button(
        "⬇️ Baixar modelo de CSV vazio",
        modelo_csv.to_csv(index=False).encode("utf-8"),
        file_name="modelo_avaliacao_lote.csv",
        mime="text/csv",
    )

    arquivo = st.file_uploader("Envie o CSV preenchido", type=["csv"])

    if arquivo is not None:
        try:
            lote = pd.read_csv(arquivo)
        except Exception as e:
            st.error(f"Não consegui ler o CSV: {e}")
            st.stop()

        faltando = [c for c in colunas_esperadas if c not in lote.columns]
        if faltando:
            st.error(f"Faltam colunas no CSV: {faltando}")
            st.stop()

        lote = lote.copy()
        lote["pedra_ano_anterior_ord"] = lote["pedra_ano_anterior"].apply(
            lambda x: ORDEM_PEDRA.index(x) if x in ORDEM_PEDRA else -1
        )
        lote["tem_historico_pedra"] = lote["pedra_ano_anterior"].isin(ORDEM_PEDRA).astype(int)
        lote["tem_ipp"] = lote["ipp"].notna().astype(int)
        lote["tem_inde_anterior"] = lote["inde_ano_anterior"].notna().astype(int)

        X_lote = lote[modelo_dict["features_num"] + modelo_dict["features_flag"] + modelo_dict["features_cat"]]
        probas = pipeline.predict_proba(X_lote)[:, 1]
        lote["probabilidade_risco"] = probas.round(3)
        lote["categoria_risco"] = [categoria_risco(p)[0] for p in probas]

        st.success(f"{len(lote)} alunos avaliados.")
        st.dataframe(
            lote[["probabilidade_risco", "categoria_risco"] +
                 [c for c in lote.columns if c not in ("probabilidade_risco", "categoria_risco")]],
            use_container_width=True,
        )

        resumo = lote["categoria_risco"].value_counts()
        st.bar_chart(resumo)

        st.download_button(
            "⬇️ Baixar resultado (CSV)",
            lote.to_csv(index=False).encode("utf-8"),
            file_name="alunos_avaliados_risco_defasagem.csv",
            mime="text/csv",
        )

st.divider()
st.caption(
    "Desenvolvido para o Datathon Passos Mágicos — Fase 5 (POSTECH). "
    "Modelo carregado de: " + (caminho_usado or "—")
)
